name: RSS Feed Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # Chạy mỗi 6 tiếng

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run index.js
        run: node index.js

      - name: Commit & push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add cache1a.json cache2a.xml
          git commit -m "Auto update cache1a & cache2a" || echo "No changes"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
